server:
    port: 9898

spring:
    datasource:
        hikari:
            connectionTimeout: 20000
            maximumPoolSize: 5
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/cupidwel
        username: cupidwel
        password: cupidwel123!

graphql:
    path: /graphql
    cors:
      allowed-origins: https://localhost:9898/
      allowed-methods: GET, POST

mabatis:
    type-aliases-package: com.example.demo.domain
    configuration:
        map-underscore-to-camel-case: true #auto change snake_case to camelCase