server:
    port: 9898

spring:
    datasource:
        hikari:
            connectionTimeout: 20000
            maximumPoolSize: 5
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/cupidwel
        username: cupidwel
        password: cupidwel123!
    graphql:
        path: /graphql
        # cors:
        #     allowed-origins: http://localhost:3000/
        #     allowed-methods: GET, POST

mybatis:
    type-aliases-package: com.example.demo.domain
    configuration:
        mapUnderscoreToCamelCase: true #auto change snake_case to camelCase

app:
    firebase-configuration-file: ./serviceAccountKey.json
    firebase-bucket: cupidwel-a193a.appspot.com

# logging:
#     level:
#         root: DEBUG
